[App]
Name = "challenge-wildfires-submission-deepmind"
Version = "1.0"
Title = "Wildfire Challenge Submission Title deepmind"
Description = "Wildfire Challenge Submission Description."
LongDescription = "about.md"
Tags = ["WILDFIRES"]

[Runtime]
Module = "src.app"
MemoryLimit = "5Gi"
MemoryReservation = "1Gi"
